services:
  tabelafipe:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: tabelafipe
    ports:
      - "8501:8501"
    volumes:
      - ./tabelafipe:/app
    restart: unless-stopped
    networks:
      - streamlit-postgresql
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - streamlit-postgresql

networks:
  streamlit-postgresql:
    driver: bridge

volumes:
  pg-data:
    driver: local
