services:
  tabelafipe:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - "./static:/tabelafipe/app/static/"
  db:
    image: postgres
    container_name: "app_db"
    restart: always
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: ''
      POSTGRES_DB: ''
      TZ: 
    volumes:
      - "./data/postgress:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"