services:
  tabelafipe:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    container_name: tabelafipe
    
    ports:
      - "8501:8501"
    volumes:
      - ./static:/tabelafipe/app/static/
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: testDB
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
    expose:
      - "5432"
